# frozen_string_literal: true

module Nii
  module Units
    autoload :Acceleration,          'nii/units/acceleration'
    autoload :Angle,                 'nii/units/angle'
    autoload :Area,                  'nii/units/area'
    autoload :Concentration,         'nii/units/concentration'
    autoload :Consumption,           'nii/units/consumption'
    autoload :CurrentDensity,        'nii/units/current_density'
    autoload :Digital,               'nii/units/digital'
    autoload :Dose,                  'nii/units/dose'
    autoload :Duration,              'nii/units/duration'
    autoload :ElectricCapacitance,   'nii/units/electric_capacitance'
    autoload :ElectricCharge,        'nii/units/electric_charge'
    autoload :ElectricConductance,   'nii/units/electric_conductance'
    autoload :ElectricCurrent,       'nii/units/electric_current'
    autoload :ElectricInductance,    'nii/units/electric_inductance'
    autoload :ElectricResistance,    'nii/units/electric_resistance'
    autoload :Energy,                'nii/units/energy'
    autoload :Force,                 'nii/units/force'
    autoload :Frequency,             'nii/units/frequency'
    autoload :Graphics,              'nii/units/graphics'
    autoload :GenericUnit,           'nii/units/generic_unit'
    autoload :Illuminance,           'nii/units/illuminance'
    autoload :Length,                'nii/units/length'
    autoload :LuminousFlux,          'nii/units/luminous_flux'
    autoload :LuminousIntensity,     'nii/units/luminous_intensity'
    autoload :MagneticFieldStrength, 'nii/units/magnetic_field_strength'
    autoload :MagneticFlux,          'nii/units/magnetic_flux'
    autoload :MagneticInduction,     'nii/units/magnetic_induction'
    autoload :Mass,                  'nii/units/mass'
    autoload :MassDensity,           'nii/units/mass_density'
    autoload :MassFraction,          'nii/units/mass_fraction'
    autoload :Portion,               'nii/units/portion'
    autoload :Power,                 'nii/units/power'
    autoload :Pressure,              'nii/units/pressure'
    autoload :PressurePerLength,     'nii/units/pressure_per_length'
    autoload :Resolution,            'nii/units/resolution'
    autoload :SolidAngle,            'nii/units/solid_angle'
    autoload :SpecificVolume,        'nii/units/specific_volume'
    autoload :Speed,                 'nii/units/speed'
    autoload :SubstanceAmount,       'nii/units/substance_amount'
    autoload :Temperature,           'nii/units/temperature'
    autoload :Torque,                'nii/units/torque'
    autoload :Typewidth,             'nii/units/typewidth'
    autoload :Voltage,               'nii/units/voltage'
    autoload :Volume,                'nii/units/volume'
    autoload :WaveNumber,            'nii/units/wave_number'
    autoload :YearDuration,          'nii/units/year_duration'
  end
end
