source 'https://rubygems.org'

ruby '3.0.0'

# minimal rails stack
gem 'rails', '~> 6.1.3', '>= 6.1.3.1'
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 5.0'
gem 'sass-rails', '>= 6'

# a few development tools
group :development do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'listen', '~> 3.3'
end

# nii
gem 'nii-rails', path: '../..'
