source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-livereload'
gem 'middleman-syntax'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby, :x64_mingw]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw, :x64_mingw]
gem 'webrick'

gem 'rouge', git: 'https://github.com/rkh/rouge.git', branch: 'rkh-fluent'
gem 'redcarpet'
